apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-remote
  template:
    metadata:
      labels:
        app: go-remote
    spec:
      containers:
      - name: go-remote
        image: adachisakura/go-remote:latest
        imagePullPolicy: IfNotPresent
        volumeMounts: #nfs mount existing code
          - name: nfs
            mountPath: /go/src
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 8080
          name: http
      volumes:
        - name: nfs
          nfs:
            path: /src
            server: 192.168.2.102 #your nfs server ip
